Repository SSGProjectStarRoad/StarRoad_admin, pull requests merged in 2024-05, with the labels that each got.

#1 Feature/Store
  build.gradle
  src/main/java/com/ssg/starroadadmin/board/entity/Answer.java
  src/main/java/com/ssg/starroadadmin/board/entity/Board.java
  src/main/java/com/ssg/starroadadmin/board/entity/BoardImage.java
  src/main/java/com/ssg/starroadadmin/coupon/entity/Coupon.java
  src/main/java/com/ssg/starroadadmin/coupon/entity/CouponHistory.java
  src/main/java/com/ssg/starroadadmin/global/config/JPAQueryFactoryConfig.java
  src/main/java/com/ssg/starroadadmin/global/entity/BaseTimeEntity.java
  src/main/java/com/ssg/starroadadmin/global/error/code/ManagerErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/code/ShopErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/ManagerException.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/ShopException.java
  src/main/java/com/ssg/starroadadmin/review/entity/Review.java
  src/main/java/com/ssg/starroadadmin/review/entity/ReviewFeedback.java
  src/main/java/com/ssg/starroadadmin/review/entity/ReviewImage.java
  src/main/java/com/ssg/starroadadmin/review/entity/ReviewLike.java
  src/main/java/com/ssg/starroadadmin/reward/entity/Reward.java
  src/main/java/com/ssg/starroadadmin/reward/entity/RewardHistory.java
  src/main/java/com/ssg/starroadadmin/shop/dto/SearchStoreRequest.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreListResponse.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreModifyRequest.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreRegisterRequest.java
  src/main/java/com/ssg/starroadadmin/shop/entity/ComplexShoppingmall.java
  src/main/java/com/ssg/starroadadmin/shop/entity/Store.java
  src/main/java/com/ssg/starroadadmin/shop/enums/StoreSortType.java
  src/main/java/com/ssg/starroadadmin/shop/repository/ComplexShoppingmallRepository.java
  src/main/java/com/ssg/starroadadmin/shop/repository/StoreRepository.java
  src/main/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/StoreService.java
  src/main/java/com/ssg/starroadadmin/shop/service/StoreServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/entity/Follow.java
  src/main/java/com/ssg/starroadadmin/user/entity/Manager.java
  src/main/java/com/ssg/starroadadmin/user/entity/Users.java
  src/main/java/com/ssg/starroadadmin/user/repository/ManagerRepository.java
  src/test/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustomImplTest.java
  src/test/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryTest.java
  src/test/java/com/ssg/starroadadmin/shop/service/StoreServiceTest.java
  src/test/java/com/ssg/starroadadmin/user/repository/ManagerRepositoryTest.java
Labels: enhancement

#2 FEAT : Add Service file
  src/main/java/com/ssg/starroadadmin/shop/service/StoreService.java
Labels: enhancement

#3 HOTFIX : Update User Table Fields
  src/main/java/com/ssg/starroadadmin/user/entity/Users.java
  src/main/java/com/ssg/starroadadmin/user/enums/ProviderType.java
Labels: documentation, enhancement

#4 H OTFIX : Refact Entity class
  build.gradle
  src/main/java/com/ssg/starroadadmin/board/entity/Answer.java
  src/main/java/com/ssg/starroadadmin/board/entity/Board.java
  src/main/java/com/ssg/starroadadmin/coupon/entity/CouponHistory.java
  src/main/java/com/ssg/starroadadmin/review/entity/Review.java
  src/main/java/com/ssg/starroadadmin/review/entity/ReviewLike.java
  src/main/java/com/ssg/starroadadmin/reward/entity/RewardHistory.java
  src/main/java/com/ssg/starroadadmin/shop/entity/Store.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/entity/Follow.java
  src/main/java/com/ssg/starroadadmin/user/entity/User.java
  src/main/java/com/ssg/starroadadmin/user/repository/UserRepository.java
Labels: bug, enhancement

#6 F EAT : S3
  build.gradle
  src/main/java/com/ssg/starroadadmin/global/S3Controller.java
  src/main/java/com/ssg/starroadadmin/global/config/S3Config.java
  src/main/java/com/ssg/starroadadmin/global/service/S3Uploader.java
  src/test/java/com/ssg/starroadadmin/global/service/NCPObjectStorageTest.java
  src/test/java/com/ssg/starroadadmin/global/service/S3UploaderTest.java
Labels: enhancement

#5 FEAT : Reward
  build.gradle
  src/main/java/com/ssg/starroadadmin/global/S3Controller.java
  src/main/java/com/ssg/starroadadmin/global/config/S3Config.java
  src/main/java/com/ssg/starroadadmin/global/service/S3Uploader.java
  src/main/java/com/ssg/starroadadmin/reward/dto/RewardListRequest.java
  src/main/java/com/ssg/starroadadmin/reward/dto/RewardListResponse.java
  src/main/java/com/ssg/starroadadmin/reward/dto/RewardRegisterRequest.java
  src/main/java/com/ssg/starroadadmin/reward/entity/Reward.java
  src/main/java/com/ssg/starroadadmin/reward/enums/RewardSortType.java
  src/main/java/com/ssg/starroadadmin/reward/repository/RewardRepository.java
  src/main/java/com/ssg/starroadadmin/reward/repository/RewardRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/reward/repository/RewardRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/reward/service/RewardService.java
  src/main/java/com/ssg/starroadadmin/reward/service/impl/RewardServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/entity/Manager.java
  src/main/java/com/ssg/starroadadmin/user/entity/User.java
  src/test/java/com/ssg/starroadadmin/global/service/NCPObjectStorageTest.java
  src/test/java/com/ssg/starroadadmin/global/service/S3UploaderTest.java
  src/test/java/com/ssg/starroadadmin/reward/repository/RewardRepositoryCustomTest.java
  src/test/java/com/ssg/starroadadmin/reward/service/RewardServiceMockTest.java
  src/test/java/com/ssg/starroadadmin/reward/service/RewardServiceTest.java
  src/test/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustomTest.java
Labels: enhancement

#7 FEAT : REVIEW
  src/main/java/com/ssg/starroadadmin/global/dto/BetweenDate.java
  src/main/java/com/ssg/starroadadmin/global/error/code/ReviewErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/code/UserErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/ReviewException.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/UserException.java
  src/main/java/com/ssg/starroadadmin/global/service/S3Uploader.java
  src/main/java/com/ssg/starroadadmin/review/dto/ReviewDetails.java
  src/main/java/com/ssg/starroadadmin/review/dto/ReviewListResponse.java
  src/main/java/com/ssg/starroadadmin/review/dto/ReviewListWithOutImagesAndFeedbacksResponse.java
  src/main/java/com/ssg/starroadadmin/review/dto/StoreReviewSearchRequest.java
  src/main/java/com/ssg/starroadadmin/review/dto/UserReviewSearchRequest.java
  src/main/java/com/ssg/starroadadmin/review/enums/ReviewSortType.java
  src/main/java/com/ssg/starroadadmin/review/repository/ReviewRepository.java
  src/main/java/com/ssg/starroadadmin/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/review/repository/ReviewRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/review/service/ReviewService.java
  src/main/java/com/ssg/starroadadmin/review/service/ReviewServiceImpl.java
  src/main/java/com/ssg/starroadadmin/shop/dto/SearchStoreRequest.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreListResponse.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreRegisterRequest.java
  src/main/java/com/ssg/starroadadmin/shop/entity/Store.java
  src/main/java/com/ssg/starroadadmin/shop/enums/Floor.java
  src/main/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/test/java/com/ssg/starroadadmin/global/service/NCPObjectStorageTest.java
  src/test/java/com/ssg/starroadadmin/global/service/S3UploaderTest.java
  src/test/java/com/ssg/starroadadmin/review/repository/ReviewRepositoryCustomTest.java
  src/test/java/com/ssg/starroadadmin/reward/service/RewardServiceMockTest.java
  src/test/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustomTest.java
  src/test/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryTest.java
  src/test/java/com/ssg/starroadadmin/shop/service/StoreServiceTest.java
  src/test/resources/application.properties
Labels: bug, enhancement

#8 FEAT : Thymeleaf Store
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  src/main/java/com/ssg/starroadadmin/global/error/code/ComplexmallErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/code/ManagerErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/ComplexmallException.java
  src/main/java/com/ssg/starroadadmin/global/service/S3Uploader.java
  src/main/java/com/ssg/starroadadmin/shop/controller/ComplexShoppingmallController.java
  src/main/java/com/ssg/starroadadmin/shop/controller/StoreController.java
  src/main/java/com/ssg/starroadadmin/shop/dto/SearchStoreRequest.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreListResponse.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreResponse.java
  src/main/java/com/ssg/starroadadmin/shop/enums/StoreSortType.java
  src/main/java/com/ssg/starroadadmin/shop/enums/StoreType.java
  src/main/java/com/ssg/starroadadmin/shop/repository/StoreRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/ComplexShoppingmallService.java
  src/main/java/com/ssg/starroadadmin/shop/service/StoreService.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/ComplexShoppingmallServiceImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/main/resources/log4j2.xml
  src/main/resources/static/img/starroad-1-no-text.png
  src/main/resources/static/img/starroad-1.png
  src/main/resources/static/scss/bootstrap/scss/_variables.scss
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/store/storeDetail.html
  src/main/resources/templates/store/storeList.html
  src/test/java/com/ssg/starroadadmin/global/component/NCPObjectStorageTest.java
  src/test/java/com/ssg/starroadadmin/global/component/S3UploaderTest.java
  src/test/java/com/ssg/starroadadmin/review/repository/ReviewRepositoryCustomTest.java
  src/test/java/com/ssg/starroadadmin/shop/service/StoreServiceTest.java
Labels: enhancement

#11 FEAT : ADD STORE & STORE MANAGER
  build.gradle
  src/main/java/com/ssg/starroadadmin/global/config/WebSecurityConfig.java
  src/main/java/com/ssg/starroadadmin/shop/controller/StoreController.java
  src/main/java/com/ssg/starroadadmin/shop/dto/StoreCreateRequest.java
  src/main/java/com/ssg/starroadadmin/shop/enums/StoreType.java
  src/main/java/com/ssg/starroadadmin/shop/service/StoreService.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/controller/ManagerController.java
  src/main/java/com/ssg/starroadadmin/user/repository/ManagerRepository.java
  src/main/java/com/ssg/starroadadmin/user/service/ManagerService.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/ManagerServiceImpl.java
  src/main/resources/templates/store/storeCreate.html
  src/main/resources/templates/store/storeList.html
  src/test/java/com/ssg/starroadadmin/global/component/S3UploaderTest.java
  src/test/java/com/ssg/starroadadmin/shop/service/StoreServiceTest.java
  src/test/java/com/ssg/starroadadmin/user/repository/ManagerRepositoryTest.java
  src/test/java/com/ssg/starroadadmin/user/service/impl/ManagerServiceImplTest.java
Labels: enhancement

#13 Create deploy.yml
  .github/workflows/ deploy.yml
  Dockerfile
  src/test/java/com/ssg/starroadadmin/shop/service/StoreServiceTest.java
Labels: enhancement

#19 INFRA : GITHUB ACTION SET-UP
  .github/workflows/ deploy.yml
  Dockerfile
Labels: enhancement

#20 BUG : Thymeleaf Layout Paths
  src/main/resources/templates/blank.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layoutTest.html
  src/main/resources/templates/review/reviewDetail.html
  src/main/resources/templates/review/reviewList.html
  src/main/resources/templates/store/storeCreate.html
  src/main/resources/templates/store/storeDetail.html
  src/main/resources/templates/store/storeList.html
  src/main/resources/templates/store/storeReviewList.html
  src/main/resources/templates/user/userDetail.html
  src/main/resources/templates/user/userList.html
  src/main/resources/templates/user/userReviewList.html
Labels: bug

#21 REFACT : WEBJARS PATHS
  build.gradle
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/review/reviewDetail.html
  src/main/resources/templates/review/reviewList.html
  src/main/resources/templates/store/storeCreate.html
  src/main/resources/templates/store/storeDetail.html
  src/main/resources/templates/store/storeList.html
  src/main/resources/templates/store/storeReviewList.html
  src/main/resources/templates/user/userDetail.html
  src/main/resources/templates/user/userReviewList.html
Labels: bug, enhancement

#23 HOTFIX : Crash Deploy File Name
  .github/workflows/deploy.yml
Labels: bug

#26 FEAT : REWARD
  src/main/java/com/ssg/starroadadmin/reward/controller/RewardController.java
  src/main/java/com/ssg/starroadadmin/reward/dto/RewardListRequest.java
  src/main/java/com/ssg/starroadadmin/reward/dto/RewardRegisterRequest.java
  src/main/java/com/ssg/starroadadmin/reward/enums/RewardSortType.java
  src/main/java/com/ssg/starroadadmin/reward/repository/RewardRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/reward/service/RewardService.java
  src/main/java/com/ssg/starroadadmin/reward/service/impl/RewardServiceImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/main/resources/templates/review/reviewList.html
  src/main/resources/templates/reward/rewardList.html
  src/test/java/com/ssg/starroadadmin/reward/service/RewardServiceMockTest.java
  src/test/java/com/ssg/starroadadmin/reward/service/RewardServiceTest.java
Labels: enhancement

#27 REFACT : STORE CONDITION GUIDE MAP
  src/main/resources/static/js/hanam-starfield.js
Labels: enhancement

#28 BUG : INCOMPLETE SECURITY
  build.gradle
  src/main/java/com/ssg/starroadadmin/global/S3Controller.java
  src/main/java/com/ssg/starroadadmin/global/config/JwtAuthenticationFilter.java
  src/main/java/com/ssg/starroadadmin/global/config/JwtTokenProvider.java
  src/main/java/com/ssg/starroadadmin/global/config/WebConfig.java
  src/main/java/com/ssg/starroadadmin/global/config/WebSecurityConfig.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/UserException.java
  src/main/java/com/ssg/starroadadmin/global/util/S3Uploader.java
  src/main/java/com/ssg/starroadadmin/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/ssg/starroadadmin/reward/service/impl/RewardServiceImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/controller/ManagerController.java
  src/main/java/com/ssg/starroadadmin/user/entity/Manager.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/ManagerDetailsServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/UserServiceImpl.java
Labels: bug

#29 FEAT : BOARD
  src/main/java/com/ssg/starroadadmin/board/controller/BoardController.java
  src/main/java/com/ssg/starroadadmin/board/dto/BoardCreateRequest.java
  src/main/java/com/ssg/starroadadmin/board/dto/BoardListResponse.java
  src/main/java/com/ssg/starroadadmin/board/dto/BoardResponse.java
  src/main/java/com/ssg/starroadadmin/board/dto/SearchBoardRequest.java
  src/main/java/com/ssg/starroadadmin/board/entity/Board.java
  src/main/java/com/ssg/starroadadmin/board/entity/BoardImage.java
  src/main/java/com/ssg/starroadadmin/board/enums/BoardCategory.java
  src/main/java/com/ssg/starroadadmin/board/enums/BoardSortType.java
  src/main/java/com/ssg/starroadadmin/board/repository/BoardImageRepository.java
  src/main/java/com/ssg/starroadadmin/board/repository/BoardRepository.java
  src/main/java/com/ssg/starroadadmin/board/repository/BoardRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/board/repository/Impl/BoardRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/board/service/BoardService.java
  src/main/java/com/ssg/starroadadmin/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/ssg/starroadadmin/global/S3Controller.java
  src/main/java/com/ssg/starroadadmin/global/error/code/BoardErrorCode.java
  src/main/java/com/ssg/starroadadmin/global/error/exception/BoardException.java
  src/main/java/com/ssg/starroadadmin/global/service/S3Uploader.java
  src/main/java/com/ssg/starroadadmin/global/util/S3Uploader.java
  src/main/java/com/ssg/starroadadmin/reward/service/impl/RewardServiceImpl.java
  src/main/resources/templates/board/boardDetail.html
  src/main/resources/templates/board/boardList.html
Labels: enhancement

#30 FEAT : COUPON HISTORY
  src/main/java/com/ssg/starroadadmin/coupon/controller/CouponController.java
  src/main/java/com/ssg/starroadadmin/coupon/dto/UserCouponRequest.java
  src/main/java/com/ssg/starroadadmin/coupon/dto/UserCouponResponse.java
  src/main/java/com/ssg/starroadadmin/coupon/entity/CouponHistory.java
  src/main/java/com/ssg/starroadadmin/coupon/enums/CouponSortType.java
  src/main/java/com/ssg/starroadadmin/coupon/repository/CouponHistoryRepository.java
  src/main/java/com/ssg/starroadadmin/coupon/repository/CouponHistoryRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/coupon/repository/impl/CouponHistoryRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/coupon/service/CouponService.java
  src/main/java/com/ssg/starroadadmin/coupon/service/impl/CouponServiceImpl.java
  src/main/resources/templates/coupon/couponHistoryList.html
Labels: enhancement

#32 FEAT : STORE DETAIL FEEDBACK
  src/main/java/com/ssg/starroadadmin/review/controller/ReviewFeedbackController.java
  src/main/java/com/ssg/starroadadmin/review/repository/ReviewFeedbackRepositoryCustom.java
  src/main/java/com/ssg/starroadadmin/review/repository/impl/ReviewFeedbackRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/review/service/ReviewFeedbackService.java
  src/main/java/com/ssg/starroadadmin/review/service/impl/ReviewFeedbackServiceImpl.java
  src/main/resources/templates/store/storeDetail.html
Labels: enhancement

#33 FEAT : Security
  build.gradle
  src/main/java/com/ssg/starroadadmin/global/config/CustomLogoutHandler.java
  src/main/java/com/ssg/starroadadmin/global/config/JwtAuthenticationFilter.java
  src/main/java/com/ssg/starroadadmin/global/config/JwtTokenProvider.java
  src/main/java/com/ssg/starroadadmin/global/config/TokenAuthenticationFilter.java
  src/main/java/com/ssg/starroadadmin/global/config/WebConfig.java
  src/main/java/com/ssg/starroadadmin/global/config/WebSecurityConfig.java
  src/main/java/com/ssg/starroadadmin/global/config/jwt/JwtProperties.java
  src/main/java/com/ssg/starroadadmin/global/config/jwt/TokenProvider.java
  src/main/java/com/ssg/starroadadmin/global/entity/CustomUserDetails.java
  src/main/java/com/ssg/starroadadmin/global/util/KeyGenerator.java
  src/main/java/com/ssg/starroadadmin/global/util/TokenGenerator.java
  src/main/java/com/ssg/starroadadmin/review/controller/ChartController.java
  src/main/java/com/ssg/starroadadmin/review/controller/ReviewController.java
  src/main/java/com/ssg/starroadadmin/review/controller/ReviewFeedbackController.java
  src/main/java/com/ssg/starroadadmin/reward/controller/RewardController.java
  src/main/java/com/ssg/starroadadmin/shop/controller/ComplexShoppingmallController.java
  src/main/java/com/ssg/starroadadmin/shop/controller/StoreController.java
  src/main/java/com/ssg/starroadadmin/user/controller/LoginController.java
  src/main/java/com/ssg/starroadadmin/user/controller/ManagerController.java
  src/main/java/com/ssg/starroadadmin/user/controller/TokenApiController.java
  src/main/java/com/ssg/starroadadmin/user/controller/UserController.java
  src/main/java/com/ssg/starroadadmin/user/dto/CreateAccessTokenRequest.java
  src/main/java/com/ssg/starroadadmin/user/dto/CreateAccessTokenResponse.java
  src/main/java/com/ssg/starroadadmin/user/dto/LoginRequest.java
  src/main/java/com/ssg/starroadadmin/user/dto/LoginResponse.java
  src/main/java/com/ssg/starroadadmin/user/dto/ManagerRegisterRequest.java
  src/main/java/com/ssg/starroadadmin/user/entity/Manager.java
  src/main/java/com/ssg/starroadadmin/user/entity/RefreshToken.java
  src/main/java/com/ssg/starroadadmin/user/entity/User.java
  src/main/java/com/ssg/starroadadmin/user/enums/ProviderType.java
  src/main/java/com/ssg/starroadadmin/user/repository/RefreshTokenRepository.java
  src/main/java/com/ssg/starroadadmin/user/service/ManagerService.java
  src/main/java/com/ssg/starroadadmin/user/service/RefreshTokenService.java
  src/main/java/com/ssg/starroadadmin/user/service/TokenService.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/ManagerDetailsServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/ManagerServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/RefreshTokenServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/TokenServiceImpl.java
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/login.html
  src/test/java/com/ssg/starroadadmin/reward/service/RewardServiceTest.java
  src/test/java/com/ssg/starroadadmin/shop/service/StoreServiceTest.java
  src/test/java/com/ssg/starroadadmin/user/service/ManagerServiceTest.java
  src/test/java/com/ssg/starroadadmin/user/service/impl/ManagerServiceImplTest.java
Labels: enhancement

#34 REFACT : CONTROLLER REQUEST PARAMETER
  src/main/java/com/ssg/starroadadmin/board/controller/BoardController.java
  src/main/java/com/ssg/starroadadmin/board/service/BoardService.java
  src/main/java/com/ssg/starroadadmin/board/service/Impl/BoardServiceImpl.java
  src/main/java/com/ssg/starroadadmin/coupon/controller/CouponController.java
  src/main/java/com/ssg/starroadadmin/coupon/repository/CouponHistoryRepository.java
  src/main/java/com/ssg/starroadadmin/coupon/repository/CouponRepository.java
  src/main/java/com/ssg/starroadadmin/coupon/repository/impl/CouponHistoryRepositoryCustomImpl.java
  src/main/java/com/ssg/starroadadmin/coupon/service/CouponService.java
  src/main/java/com/ssg/starroadadmin/coupon/service/impl/CouponServiceImpl.java
  src/main/java/com/ssg/starroadadmin/global/config/TokenAuthenticationFilter.java
  src/main/java/com/ssg/starroadadmin/global/config/jwt/TokenProvider.java
  src/main/java/com/ssg/starroadadmin/global/entity/CustomUserDetails.java
  src/main/java/com/ssg/starroadadmin/review/controller/ChartController.java
  src/main/java/com/ssg/starroadadmin/review/controller/ReviewController.java
  src/main/java/com/ssg/starroadadmin/review/controller/ReviewFeedbackController.java
  src/main/java/com/ssg/starroadadmin/review/service/ChartService.java
  src/main/java/com/ssg/starroadadmin/review/service/ReviewFeedbackService.java
  src/main/java/com/ssg/starroadadmin/review/service/ReviewService.java
  src/main/java/com/ssg/starroadadmin/review/service/impl/ChartServiceImpl.java
  src/main/java/com/ssg/starroadadmin/review/service/impl/ReviewFeedbackServiceImpl.java
  src/main/java/com/ssg/starroadadmin/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/ssg/starroadadmin/reward/controller/RewardController.java
  src/main/java/com/ssg/starroadadmin/reward/service/RewardService.java
  src/main/java/com/ssg/starroadadmin/reward/service/impl/RewardServiceImpl.java
  src/main/java/com/ssg/starroadadmin/shop/controller/ComplexShoppingmallController.java
  src/main/java/com/ssg/starroadadmin/shop/controller/StoreController.java
  src/main/java/com/ssg/starroadadmin/shop/service/ComplexShoppingmallService.java
  src/main/java/com/ssg/starroadadmin/shop/service/StoreService.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/ComplexShoppingmallServiceImpl.java
  src/main/java/com/ssg/starroadadmin/shop/service/impl/StoreServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/controller/ManagerController.java
  src/main/java/com/ssg/starroadadmin/user/controller/UserController.java
  src/main/java/com/ssg/starroadadmin/user/repository/ManagerRepository.java
  src/main/java/com/ssg/starroadadmin/user/service/UserService.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/FollowServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/ManagerServiceImpl.java
  src/main/java/com/ssg/starroadadmin/user/service/impl/UserServiceImpl.java
Labels: bug
